# makefile

all: test1 test2 test3

test1: test1.c psiskv_lib.c
	gcc -g -Wall test1.c psiskv_lib.c -o  test1

test2: test2.c psiskv_lib.c
	gcc -g -Wall test2.c psiskv_lib.c -o  test2

test3: test3.c psiskv_lib.c
	gcc -g -Wall test3.c psiskv_lib.c -o  test3



